### ISSUE TITLE
Global out-of-bounds

### ISSUE THREAD

**Issue by xorseed** [robertdavidgraham/masscan#44]
ASan found this

```
==10003== ERROR: AddressSanitizer: global-buffer-overflow on address 0x000000465826 at pc 0x4093d9 bp 0x7fff8d1119f0 sp 0x7fff8d1119e8
READ of size 1 at 0x000000465826 thread T0
    #0 0x4093d8 (/masscan/bin/masscan+0x4093d8)
    #1 0x40d550 (/masscan/bin/masscan+0x40d550)
    #2 0x406511 (/masscan/bin/masscan+0x406511)
    #3 0x7f3843afad84 (/lib64/libc-2.17.so+0x21d84)
    #4 0x407e24 (/masscan/bin/masscan+0x407e24)
0x000000465826 is located 6 bytes to the right of global variable '*.LC16 (src/templ-payloads.c)' (0x465800) of size 32
0x000000465826 is located 26 bytes to the left of global variable '*.LC17 (src/templ-payloads.c)' (0x465840) of size 51
Shadow bytes around the buggy address:
  0x000080084ab0: f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9 07 f9 f9 f9
  0x000080084ac0: f9 f9 f9 f9 00 00 00 00 06 f9 f9 f9 f9 f9 f9 f9
  0x000080084ad0: 00 00 00 00 05 f9 f9 f9 f9 f9 f9 f9 00 00 00 05
  0x000080084ae0: f9 f9 f9 f9 00 00 01 f9 f9 f9 f9 f9 06 f9 f9 f9
  0x000080084af0: f9 f9 f9 f9 00 00 00 00 00 00 00 04 f9 f9 f9 f9
=>0x000080084b00: 00 00 00 00[f9]f9 f9 f9 00 00 00 00 00 00 03 f9
  0x000080084b10: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080084b20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080084b30: 00 00 00 00 00 00 00 00 00 00 00 00 00 01 f9 f9
  0x000080084b40: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x000080084b50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:     fa
  Heap righ redzone:     fb
  Freed Heap region:     fd
  Stack left redzone:    f1
  Stack mid redzone:     f2
  Stack right redzone:   f3
  Stack partial redzone: f4
  Stack after return:    f5
  Stack use after scope: f8
  Global redzone:        f9
  Global init order:     f6
  Poisoned by user:      f7
  ASan internal:         fe
```

any idea for better payload memory management ?

```
0x4093d8 is in payload_add (src/templ-payloads.c:444).
439             exit(1); /* out of memory */
440 
441         p->port = rangelist_pick(ports, i);
442         p->source_port = source_port;
443         p->length = (unsigned)length;
444         memcpy(p->buf, buf, length);
445         p->xsum = partial_checksum(buf, length);
446         p->set_cookie = set_cookie;
447 
448         /* insert in sorted order */
```

```
0x40d550 is in payloads_create (src/templ-payloads.c:710).
705         if (length == 0xFFFFFFFF)
706             length = (unsigned)strlen(hard_coded_payloads[i].buf);
707         
708         /* Add this to our real payloads. This will get overwritten
709          * if the user adds their own with the same port */
710         payload_add(payloads,
711                     (const unsigned char*)hard_coded_payloads[i].buf,
712                     length,
713                     &list,
714                     hard_coded_payloads[i].source_port,
```

```
0x406511 is in main (src/main.c:1257).
1252        masscan->wait = 10; /* how long to wait for responses when done */
1253        masscan->max_rate = 100.0; /* max rate = hundred packets-per-second */
1254        masscan->nic_count = 1;
1255        masscan->shard.one = 1;
1256        masscan->shard.of = 1;
1257        masscan->payloads = payloads_create();
1258        strcpy_s(   masscan->rotate_directory,
1259                    sizeof(masscan->rotate_directory),
1260                    ".");
1261    
```

**Comment by gvanem** [comment]
I get the same on Windows with MSVC or clang-cl:
```
==10636==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7ff66854a25f at pc 0x7ff66848e38c bp 0x00d488d2e320 sp 0x00d488d2e320
READ of size 1 at 0x7ff66854a25f thread T0
    #0 0x7ff66848e38b in partial_checksum F:\MinGW32\src\inet\network-scanners\MassScan\src\templ-payloads.c:487
    #1 0x7ff66848e38b in payloads_datagram_add F:\MinGW32\src\inet\network-scanners\MassScan\src\templ-payloads.c:645
    #2 0x7ff66848e38b in payloads_udp_create F:\MinGW32\src\inet\network-scanners\MassScan\src\templ-payloads.c:848
    #3 0x7ff668434b1d in main F:\MinGW32\src\inet\network-scanners\MassScan\src\main.c:1605
    #4 0x7ff66849ce37 in invoke_main D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    #5 0x7ff66849ce37 in __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    #6 0x7ff89ffc7373  (C:\Windows\System32\KERNEL32.DLL+0x180017373)
    #7 0x7ff8a16bcc90  (C:\Windows\SYSTEM32\ntdll.dll+0x18004cc90)

0x7ff66854a25f is located 0 bytes after global variable '<C++ string literal>' defined in 'templ-payloads.c:77:16' (0x7ff66854a240) of size 31
0x7ff66854a25f is located 33 bytes before global variable '<C++ string literal>' defined in 'templ-payloads.c:88:8' (0x7ff66854a280) of size 25
SUMMARY: AddressSanitizer: global-buffer-overflow F:\MinGW32\src\inet\network-scanners\MassScan\src\templ-payloads.c:487 in partial_checksum
```

A very old issue; time for a fix?
